### ISSUE TITLE
Upgrade auto terminate free trials

### ISSUE THREAD

**Issue by dkuzik** [Katamaze/WHMCS-Free-Action-Hooks#52]
Any way you can upgrade AutoTerminateFreeTrialsAfterXMinutes.php 
using WHMCS 8.8
PHP 7.4

worked with wmcs 8.5 php 7.4

**Comment by Remitur** [comment]
The code is quite simple, and I can't see any reason it should not work with WHMCS 8.5 too... what's exactly the issue you're experiencing?

**Comment by dkuzik** [comment]
This is what I get for error. Using PHP 7.4 and whmcs 8.8 was working fine
on 8.5 before upgrade

Error: TypeError: Argument 1 passed to
Illuminate\Database\Query\Builder::cleanBindings() must be of the type
array, null given, called in /www/wwwroot//billing/vendor/illuminate/database/Query/Builder.php
on line 918 and defined in /www/wwwroot//billing/vendor/illuminate/database/Query/Builder.php:3020
Stack trace: #0 /www/wwwroot//billing/vendor/illuminate/database/Query/Builder.php(918):
Illuminate\Database\Query\Builder->cleanBindings() #1 /www/wwwroot//billing/includes/hooks/AutoTerminateFreeTrialsAfterXMinutes.php(45):
Illuminate\Database\Query\Builder->whereIn() #2 /www/wwwroot/billing/vendor/whmcs/whmcs-foundation/lib/Hook/Manager.php(0):
WHMCS\Utility\SafeInclude::{closure}() #3 /www/wwwroot/billing/vendor/illuminate/support/Facades/Facade.php(261):
WHMCS\Hook\Manager->run() #4 /www/wwwroot/billing/includes/functions.php(0):
Illuminate\Support\Facades\Facade::__callStatic() #5 /www/wwwroot/billing/vendor/whmcs/whmcs-foundation/lib/Cron/Console/Command/AbstractCronCommand.php(0):
run_hook() #6 /www/wwwroot/billing/vendor/whmcs/whmcs-foundation/lib/Cron/Console/Command/AbstractCronCommand.php(0):
WHMCS\Cron\Console\Command\AbstractCronCommand->tearDown() #7 /www/wwwroot/billing/vendor/symfony/console/Command/Command.php(298):
WHMCS\Cron\Console\Command\AbstractCronCommand->execute() #8 /www/wwwroot/billing/vendor/symfony/console/Application.php(1028):
Symfony\Component\Console\Command\Command->run() #9 /www/wwwroot/billing/vendor/symfony/console/Application.php(299):
Symfony\Component\Console\Application->doRunCommand() #10 /www/wwwroot/billing/vendor/symfony/console/Application.php(171):
Symfony\Component\Console\Application->doRun() #11 /www/wwwroot/billing/crons/cron.php(0):
Symfony\Component\Console\Application->run() #12 {main}
